authentication/urls.py
from django.urls import path
from authentication.views import register_user, login_user, logout_user

app_name = 'authentication'

urlpatterns = [
    path('register/', register_user, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

bekas_berkelas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('profile/', include('review_rating.urls')),
    path('forum/', include('forum.urls')),
    path('katalog/', include('product_catalog.urls')),
    path('dashboard/', include('user_dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import main

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserRole(models.TextChoices) :
    ADMIN = 'ADM', 'Admin',
    BUYER = 'BUY', 'Buyer',
    SELLER = 'SEL', 'Seller'

class UserProfile(models.Model) :
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    email = models.EmailField()
    no_telp = models.CharField(default='-', max_length=12)
    role = models.CharField(default=UserRole.BUYER, choices=UserRole.choices, max_length=3)
    profile_picture = models.URLField(max_length=500, blank=True, null=True)
    profile_picture_id = models.CharField(max_length=300,  blank=True, null=True)
    is_verified = models.BooleanField(default=False)

authentication/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile, UserRole
from user_dashboard.models import BuyerProfile, SellerProfile, AdminProfile

class RegisterForm(UserCreationForm) :
    name = forms.CharField(max_length = 300, required = True)
    email = forms.EmailField(required = True)
    no_telp = forms.CharField(max_length = 12, required = True)
    role = forms.ChoiceField(
        choices = UserRole.choices,
        initial = UserRole.BUYER,
        required = True
    )
    profile_picture = forms.ImageField(required = False)
    
    class Meta :
        model = User
        fields = ('username', 'name', 'email', 'no_telp', 'role', 'password1', 'password2')
    
    def save(self, commit=True) :
        user = super().save(commit = False)
        
        if commit :
            user.save()
            user_profile = UserProfile.objects.create(
                user = user,
                name = self.cleaned_data['name'],
                email = self.cleaned_data['email'],
                no_telp = self.cleaned_data['no_telp'],
                role = self.cleaned_data['role'],
            )

            if user_profile.role == UserRole.ADMIN:
                AdminProfile.objects.create(user_profile=user_profile)
            elif user_profile.role == UserRole.BUYER:
                BuyerProfile.objects.create(user_profile=user_profile)
            elif user_profile.role == UserRole.SELLER:
                SellerProfile.objects.create(user_profile=user_profile)
            else:
                raise ValueError("Invalid user role")

        return user

authentication/views.py
import json
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.conf import settings
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def register_user(request):
    if request.method == "POST":
        data = request.POST
        print(data)
        
        form = RegisterForm(data)
        if form.is_valid():
            if form.cleaned_data['role'] == 'ADM' and form.cleaned_data['password1'] != settings.ADMIN_ACCOUNT_SECRET_TOKEN:
                return JsonResponse({
                    'status': 'failed',
                    'message': 'Invalid Admin Credentials'
                }, status=400)
            
            form.save()
            return JsonResponse({
                'status': 'success',
                'message': 'Your account has been successfully created!'
            }, status=200)
        else:
            return JsonResponse({
                'status': 'failed',
                'message': 'Failed to create account',
                'errors': form.errors
            }, status=400)
            
    form = RegisterForm()
    context = {'form': form}
    return render(request, 'register.html', context)

@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        try:
            if request.content_type == 'application/json':
                data = json.loads(request.body)
                username = data.get('username')
                password = data.get('password')
            else:
                username = request.POST.get('username')
                password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                login(request, user)
                return JsonResponse({
                    'status': True,
                    'username': user.username,
                    'id': user.id,
                    'role': user.userprofile.role,
                    'message': 'Login successful!'
                }, status=200)
            else:
                return JsonResponse({
                    "status": "failed",
                    "message": "Invalid username or password"
                }, status=401)
                
        except json.JSONDecodeError:
            return JsonResponse({
                'status': 'failed',
                'message': 'Invalid JSON data'
            }, status=400)

    return render(request, 'login.html')

@csrf_exempt
def logout_user(request):
    logout(request)
    return JsonResponse({
        "status": "success",
        "message": "Successfully logged out!"
    }, status=200)

authentication/templates/login.html
{% extends 'base.html' %} {% load static %} 

{% block meta %}
<title>Login | BekasBerkelas</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex flex-col items-center justify-center w-full bg-blue-100 px-4 py-12">
    <div class="max-w-md w-full space-y-8 bg-white p-8 rounded-xl shadow-lg">
        <div class="w-full flex justify-center mb-8">
            <img src="{% static 'image/logo-text.png' %}" alt="Logo" class="h-[100px]">
        </div>
        <form class="mt-8 space-y-6" method="POST">
            {% csrf_token %}
            <div class="rounded-md shadow-sm space-y-2">
                <div>
                    <label for="username" class="sr-only">Username</label>
                    <input id="username" name="username" type="text" required class="appearance-none albert-sans-semibold rounded-lg relative block w-full px-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Username">
                </div>
                <div>
                    <label for="password" class="sr-only">Password</label>
                    <input id="password" name="password" type="password" required class="appearance-none albert-sans-semibold rounded-lg relative block w-full px-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Password">
                </div>
            </div>

            <div>
                <button type="submit" class="group albert-sans-semibold relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-400 hover:bg-blue-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition duration-150 ease-in-out">
                    Log In
                </button>
            </div>
        </form>

        {% if messages %}
        <div class="mt-4 space-y-2 albert-sans-semibold">
        {% for message in messages %}
        {% if message.tags == "success" %}
                <div class="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 rounded-r" role="alert">
                    <p class="font-bold">Success</p>
                    <p>{{ message }}</p>
                </div>
            {% elif message.tags == "error" %}
                <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 rounded-r" role="alert">
                    <p class="font-bold">Error</p>
                    <p>{{ message }}</p>
                </div>
            {% else %}
                <div class="bg-blue-100 border-l-4 border-blue-500 text-blue-700 p-4 rounded-r" role="alert">
                    <p class="font-bold">Info</p>
                    <p>{{ message }}</p>
                </div>
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}

        <div class="text-center mt-6 albert-sans-semibold">
            <p class="text-sm text-[#1f1c61]">
                Don't have an account yet?
                <a href="{% url 'authentication:register' %}" class="font-medium text-blue-700 hover:text-blue-800 transition duration-150 ease-in-out">
                    Register Now
                </a>
            </p>
        </div>
    </div>
</div>

<script src="{% static 'js/auth.js>' %}"></script>
{% endblock content %}

authentication/templates/register.html
{% extends 'base.html' %} {% load static %} 

{% block meta %}
<title>Register | BekasBerkelas</title>
{% endblock meta %}

{% block content %}

<div class="min-h-screen flex flex-col md:flex-row w-screen bg-blue-100 px-4 pt-0 md:py-6 sm:px-6 lg:px-8">
    <div class="w-full md:w-1/2 flex items-center justify-center pt-8 mb-8 md:mb-0 md:ml-[5%]">
        <img src="{% static 'image/logo-text.png' %}" alt="Logo" class="h-40 md:h-60 lg:h-80">
    </div>

    <div class="w-full md:w-1/2 md:max-w-md space-y-8 bg-white p-8 rounded-xl shadow-lg albert-sans-semibold md:mr-[15%] mb-8 md:mb-0">        
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <label for="username">Username</label>
                <input id="username" name="username" type="text" required class="appearance-none albert-sans-semibold rounded-lg relative block w-full px-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Username">
            </div>

            <div class="mt-2 relative">
                <label for="name">Name</label>
                <input id="name" name="name" type="text" required class="appearance-none albert-sans-semibold rounded-lg relative block w-full px-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Name">
            </div>

            <div class="mt-2 relative">
                <label for="email">Email</label>
                <input id="email" name="email" type="text" required class="appearance-none albert-sans-semibold rounded-lg relative block w-full px-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Email">
            </div>

            <div class="mt-2 relative">
                <label for="no_telp">No Telp</label>
                <input id="no_telp" name="no_telp" type="text" required class="appearance-none albert-sans-semibold rounded-lg relative block w-full px-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="No Telp">
            </div>

            <div class="mt-2 relative">
                <label for="role">User Role</label>
                <div class="relative">
                    <select id="role" name="role" required class="appearance-none rounded-lg relative block w-full px-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
                        <option value="" selected class="albert-sans-semibold">Choose role</option>
                        <option value="BUY" class="albert-sans-semibold">Buyer</option>
                        <option value="SEL" class="albert-sans-semibold">Seller</option>
                    </select>
                    <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                        <svg class="h-4 w-4 fill-current" viewBox="0 0 20 20">
                            <path d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"/>
                        </svg>
                    </div>
                </div>
            </div>

            <div class="mt-2 relative">
                <label for="password1">Password</label>
                <input id="password1" name="password1" type="password" required class="appearance-none albert-sans-semibold rounded-lg relative block w-full px-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Password">
            </div>

            <div class="mt-2 relative">
                <label for="password2">Confirm Password</label>
                <input id="password2" name="password2" type="password" required class="appearance-none albert-sans-semibold rounded-lg relative block w-full px-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Confirm Password">
            </div>

            <div class="mt-8 relative">
                <button type="submit" class="group albert-sans-semibold relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-400 hover:bg-blue-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition duration-150 ease-in-out">
                    Register
                </button>
            </div>
        </form>

        {% if messages %}
        <div class="mt-4 space-y-2">
        {% for message in messages %}
        <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 rounded-r" role="alert">
            <p class="font-bold">Error</p>
            <p>{{ message }}</p>
        </div>
        {% endfor %}
        </div>
        {% endif %}

        <div class="text-center mt-8 albert-sans-semibold">
            <p class="text-sm text-[#1f1c61]">
                Already have an account?
                <a href="{% url 'authentication:login' %}" class="font-medium text-blue-700 hover:text-blue-800 transition duration-150 ease-in-out">
                    Login Now
                </a>
            </p>
        </div>
    </div>
</div>

<script src="{% static 'js/auth.js' %}"></script>
{% endblock content %}