bekas_berkelas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('profile/', include('review_rating.urls')),
    path('forum/', include('forum.urls')),
    path('katalog/', include('product_catalog.urls')),
    path('dashboard/', include('user_dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import main

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, add_to_wishlist, edit_wishlist, remove_from_wishlist, show_json, get_wishlist_item, get_wishlist_car_ids, add_wishlist_flutter, edit_wishlist_flutter, remove_wishlist_flutter

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='wishlist_page'),
    path('show_wishlist', show_wishlist, name='show_wishlist'),
    path('add/<uuid:car_id>', add_to_wishlist, name='add_to_wishlist'),
    path('edit/<uuid:wishlist_id>', edit_wishlist, name='edit_wishlist'),
    path('remove/<uuid:wishlist_id>', remove_from_wishlist, name='remove_from_wishlist'),
    path('json', show_json, name='show_json'),
    path('get_wishlist_item/<uuid:wishlist_id>/', get_wishlist_item, name='get_wishlist_item'),
    path('car_ids/', get_wishlist_car_ids, name='get_wishlist_car_ids'),
    path('add_wishlist/<uuid:car_id>/', add_wishlist_flutter, name='add_wishlist_flutter'),
    path('edit_wishlist/<uuid:wishlist_id>/', edit_wishlist_flutter, name='edit_wishlist_flutter'),
    path('remove_wishlist/<uuid:wishlist_id>/', remove_wishlist_flutter, name='remove_wishlist_flutter'),
]

wishlist/models.py
from django.db import models
from django.contrib.auth.models import User
from product_catalog.models import Car
import uuid

class Wishlist(models.Model):
    
    PRIORITY_CHOICES = [
        (1, 'Rendah'),
        (2, 'Sedang'),
        (3, 'Tinggi')
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, null=True)
    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=1)
    
    class Meta:
        unique_together = ('user', 'car')
        ordering = ['-priority']

    def __str__(self):
        return f"{self.user.username}'s wishlist - {self.car.name} (Priority: {self.get_priority_display()})"

wishlist/forms.py
from django import forms
from .models import Wishlist

class WishlistForm(forms.ModelForm):
    class Meta:
        model = Wishlist
        fields = ['priority']

wishlist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Wishlist
from product_catalog.models import Car
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
import json
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

@require_POST
@login_required(login_url='/auth/login')
def add_to_wishlist(request, car_id):
    try:
        car = get_object_or_404(Car, id=car_id)
        user = request.user
            
        try:
            wishlist_item, created = Wishlist.objects.get_or_create(user=user, car=car, defaults={'priority':'1'})
            
            if created:
                return JsonResponse({'status': 'success','action': 'added','message': 'Menambahkan ke wishlist'})
            else:
                wishlist_item.delete()
                return JsonResponse({'status': 'success','action': 'removed','message': 'Menghapus dari wishlist'})
                
        except Exception as e:
            return JsonResponse({'status': 'error','message': f'Error with wishlist operation: {str(e)}'}, status=500)
            
    except Exception as e:
        return JsonResponse({'status': 'error','message': str(e)}, status=500)

@login_required(login_url='/auth/login')
def show_wishlist(request):
    priority_filter = request.GET.get('priority', None)
    wishlists = Wishlist.objects.filter(user=request.user)
    
    if priority_filter:
        wishlists = wishlists.filter(priority=priority_filter)
        
    context = {'wishlists': wishlists, 'selected_priority': priority_filter, 'priority_choices': Wishlist.PRIORITY_CHOICES}
    return render(request, 'wishlist.html', context)

@csrf_exempt
@login_required(login_url='/auth/login')
def edit_wishlist(request, wishlist_id):
    wishlist = get_object_or_404(Wishlist, id=wishlist_id, user=request.user)
    
    if request.method == 'POST':
        priority_map = {'Rendah': 1, 'Sedang': 2, 'Tinggi': 3}
        new_priority = request.POST.get('priority')
        wishlist.priority = priority_map.get(new_priority, 1)
        wishlist.save()
        return redirect('wishlist:show_wishlist')
    
    return render(request, 'edit_wishlist.html', {'wishlist': wishlist})

@csrf_exempt
@require_POST
@login_required(login_url='/auth/login')
def remove_from_wishlist(request, wishlist_id):
    wishlist = get_object_or_404(Wishlist, id=wishlist_id, user=request.user)
    wishlist.delete()
    return HttpResponseRedirect(reverse('wishlist:show_wishlist'))

def show_json(request):
    wishlists = Wishlist.objects.filter(user=request.user)
    data = []
    for wishlist in wishlists:
        car = wishlist.car
        data.append({
            'id': str(wishlist.pk),
            'image_url': car.image_url,
            'car_name': car.car_name,
            'price': car.price,
            'brand': car.brand,
            'year': car.year,
            'mileage': car.mileage,
            'priority': wishlist.priority,
        })
    return JsonResponse(data, safe=False)

def get_wishlist_item(request, wishlist_id):
    wishlist = get_object_or_404(Wishlist, id=wishlist_id, user=request.user)
    data = {
        'id': str(wishlist.id),
        'image_url': wishlist.car.image_url,
        'car_name': wishlist.car.car_name,
        'price': wishlist.car.price,
        'brand': wishlist.car.brand,
        'year': wishlist.car.year,
        'mileage': wishlist.car.mileage,
        'priority': wishlist.priority,
    }
    return JsonResponse(data, safe=False)

@csrf_exempt
def get_wishlist_car_ids(request):
    try:
        wishlist_items = Wishlist.objects.filter(user=request.user)
        car_ids = [str(item.car.id) for item in wishlist_items]
        return JsonResponse({'car_ids': car_ids})
    except Wishlist.DoesNotExist:
        return JsonResponse({'car_ids': []})

@csrf_exempt
@require_POST
def add_wishlist_flutter(request, car_id):
    try:
        car = get_object_or_404(Car, id=car_id)
        user = request.user
        wishlist_item, created = Wishlist.objects.get_or_create(user=user, car=car, defaults={'priority':'1'})
        if created:
            return JsonResponse({'status': 'success', 'action': 'added', 'message': 'Added to wishlist'})
        else:
            wishlist_item.delete()
            return JsonResponse({'status': 'success', 'action': 'removed', 'message': 'Removed from wishlist'})
    except Exception as e:
        return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
    

@csrf_exempt
@require_POST
def edit_wishlist_flutter(request, wishlist_id):
    try:
        wishlist = get_object_or_404(Wishlist, id=wishlist_id, user=request.user)
        new_priority = request.POST.get('priority')
        wishlist.priority = new_priority
        wishlist.save()
        return JsonResponse({'status': 'success', 'message': 'Priority updated successfully.'}, status=200  )
    except ValueError as e:
        return JsonResponse({'status': 'error', 'message': str(e)}, status=400)
    except Wishlist.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'Wishlist not found.'}, status=404)

@csrf_exempt
@require_POST
def remove_wishlist_flutter(request, wishlist_id):
    try:
        wishlist = get_object_or_404(Wishlist, id=wishlist_id, user=request.user)
        wishlist.delete()
        return JsonResponse({'status': 'success'})
    except Exception as e:
        return JsonResponse({"status": "error", "message": str(e)}, status=500)
    except Wishlist.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'Wishlist entry not found.'}, status=404)

wishlist/templates/edit_wishlist.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Edit Wish List | BekasBerkelas</title>
{% endblock meta %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="bg-blue-100 min-h-screen py-10 pt-32 flex flex-col items-center">
        <div class="w-full max-w-xs mx-auto bg-blue-100">
            <h1 class="text-center text-3xl sm:text-3xl md:text-4xl font-bold text-[#1F1C61] albert-sans mb-6">
                Edit Wish List
            </h1>

            <form method="POST" class="bg-white shadow-lg rounded-lg p-6 space-y-6">
                {% csrf_token %}
                
                <div class="text-center">
                    <p class="text-lg text-[#157A70] font-normal">Prioritas Saat Ini: 
                        <span class="font-semibold">
                            {{ wishlist.get_priority_display }}
                        </span>
                    </p>
                </div>

                <div class="flex flex-col items-center space-y-2">
                    <label for="priority" class="text-[#1F1C61] font-bold text-lg">Prioritas Baru:</label>
                    <select name="priority" class="w-36 border border-gray-300 rounded-md px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 text-[#07288B]">
                        <option value="Rendah" {% if wishlist.priority == 'Rendah' %}selected{% endif %}>Rendah</option>
                        <option value="Sedang" {% if wishlist.priority == 'Sedang' %}selected{% endif %}>Sedang</option>
                        <option value="Tinggi" {% if wishlist.priority == 'Tinggi' %}selected{% endif %}>Tinggi</option>
                    </select>
                </div>

                <div class="flex justify-center space-x-4 pt-4">
                    <button type="submit" class="bg-[#174FF3] hover:bg-[#0A39C4] text-white font-medium px-6 py-2 rounded-lg transition duration-300 shadow-sm">
                        Simpan
                    </button>
                    <a href="{% url 'wishlist:show_wishlist' %}" class="bg-red-500 hover:bg-red-600 text-white font-medium px-6 py-2 rounded-lg transition duration-300 shadow-sm">
                        Cancel
                    </a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

wishlist/templates/wishlist.html
{% extends 'base.html' %} 
{% load static %} 

{% block meta %}
    <title> Wish List | BekasBerkelas </title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% endblock meta %} 

{% block content %}
    {% include 'navbar.html' %}
    <div class="bg-blue-100 min-h-screen py-10 pt-32">
        <div class="container mx-auto px-4">
            <h1 class="text-center text-4xl text-[#1F1C61] font-bold albert-sans mb-6">Wish List</h1>
            
            <div class="flex flex-col items-center mb-8">
                <form method="get" class="flex flex-col items-center gap-2">
                    <label class="text-xl text-[#1F1C61] font-semibold albert-sans">Berdasarkan prioritas:</label>
                    <div>
                        <select name="priority" 
                            class="border border-[#07288B] text-[#07288B] rounded-md px-3 py-2 mt-2" 
                            onchange="this.form.submit()">
                        <option value="" class="text-[#07288B] albert-sans">Semua</option>
                        {% for value, label in priority_choices %}
                        <option value="{{ value }}" 
                                class="text-[##07288B] albert-sans"
                                {% if selected_priority == value|stringformat:"i" %}selected{% endif %}>
                            {{ label }}
                        </option>
                        {% endfor %}
                        </select>
                    </div>
                </form>
            </div>
            
            <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
                {% if wishlists %}
                    {% for item in wishlists %}
                    <div class="bg-white border-2 border-[#0A39C4] rounded-lg shadow-lg p-4" id="wishlist-item-{{ item.id }}">
                        <div class="relative">
                            <img src="{{ item.car.image_url }}" alt="{{ item.car.name }}" class="w-full h-48 object-cover rounded-t-md mb-4">
                        </div>
                        <div>
                            <h2 class="text-center text-xl text-[#1F1C61] font-bold albert-sans mb-2">{{ item.car.car_name }}</h2>
                            <p class="text-left text-lg text-[#07288B] font-semibold albert-sans mb-1">Rp {{ item.car.price }}</p>
                            <p class="text-left text-base text-black font-albert-sans">{{ item.car.brand }}</p>
                            <p class="text-left text-base text-black font-albert-sans">{{ item.car.year }}</p>
                            <p class="text-left text-base text-black font-albert-sans">{{ item.car.mileage }} km</p>
                            
                            <div class="mt-3 flex flex-col items-center">
                                <span class="text-sm text-[#0A39C4] font-albert-sans mb-2">Prioritas: 
                                    {% if item.priority == 1 %}Rendah
                                    {% elif item.priority == 2 %}Sedang
                                    {% else %}Tinggi{% endif %}
                                </span>
                                
                                <div class="flex items-center justify-center space-x-2">
                                    <a href="{% url 'wishlist:edit_wishlist' wishlist_id=item.id %}" 
                                       class="bg-[#174FF3] hover:bg-[#0A39C4] text-white font-semibold font-albert-sans px-4 py-2 rounded-lg">
                                        Edit
                                    </a>
                                    
                                    <form action="{% url 'wishlist:remove_from_wishlist' wishlist_id=item.id %}" method="post" class="inline-block">
                                        {% csrf_token %}
                                        <button type="submit" class="bg-[#FB3748] hover:bg-[#D00416] text-white font-semibold font-albert-sans px-4 py-2 rounded-lg">
                                            Delete
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>                    
                    </div>
                    {% endfor %}
                    
                {% else %}
                    <p class="text-center text-lg text-black font-albert-sans col-span-4">Belum ada mobil dalam Wish List</p>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock content %}